---
engines:
  duplication:
    enabled: false
  eslint:
    enabled: true
  fixme:
    enabled: true
ratings:
  paths:
  - "**.js"
exclude_paths:
- coverage/
- test/
- docs/
- examples/
- node_modules/
- out/